// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MAC_MAC,hls_ip_2022_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=6.301000,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1756,HLS_SYN_LUT=1755,HLS_VERSION=2022_2}" *)

module MAC (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a,
        b,
        c,
        j,
        ap_return
);

parameter    ap_ST_fsm_state1 = 20'd1;
parameter    ap_ST_fsm_state2 = 20'd2;
parameter    ap_ST_fsm_state3 = 20'd4;
parameter    ap_ST_fsm_state4 = 20'd8;
parameter    ap_ST_fsm_state5 = 20'd16;
parameter    ap_ST_fsm_state6 = 20'd32;
parameter    ap_ST_fsm_state7 = 20'd64;
parameter    ap_ST_fsm_state8 = 20'd128;
parameter    ap_ST_fsm_state9 = 20'd256;
parameter    ap_ST_fsm_state10 = 20'd512;
parameter    ap_ST_fsm_state11 = 20'd1024;
parameter    ap_ST_fsm_state12 = 20'd2048;
parameter    ap_ST_fsm_state13 = 20'd4096;
parameter    ap_ST_fsm_state14 = 20'd8192;
parameter    ap_ST_fsm_state15 = 20'd16384;
parameter    ap_ST_fsm_state16 = 20'd32768;
parameter    ap_ST_fsm_state17 = 20'd65536;
parameter    ap_ST_fsm_state18 = 20'd131072;
parameter    ap_ST_fsm_state19 = 20'd262144;
parameter    ap_ST_fsm_state20 = 20'd524288;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] a;
input  [31:0] b;
input  [31:0] c;
input  [31:0] j;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [19:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_start;
wire    grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_done;
wire    grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_idle;
wire    grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_ready;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_z_5_out;
wire    grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_z_5_out_ap_vld;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_161_p_din0;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_161_p_din1;
wire    grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_161_p_ce;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_165_p_din0;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_165_p_din1;
wire    grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_165_p_ce;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_169_p_din0;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_169_p_din1;
wire   [4:0] grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_169_p_opcode;
wire    grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_169_p_ce;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_173_p_din0;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_173_p_din1;
wire   [1:0] grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_173_p_opcode;
wire    grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_173_p_ce;
wire    grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_start;
wire    grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_done;
wire    grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_idle;
wire    grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_ready;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_x_2_out;
wire    grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_x_2_out_ap_vld;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_y_out;
wire    grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_y_out_ap_vld;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_173_p_din0;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_173_p_din1;
wire   [1:0] grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_173_p_opcode;
wire    grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_173_p_ce;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_161_p_din0;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_161_p_din1;
wire    grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_161_p_ce;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_165_p_din0;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_165_p_din1;
wire    grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_165_p_ce;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_169_p_din0;
wire   [31:0] grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_169_p_din1;
wire   [4:0] grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_169_p_opcode;
wire    grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_169_p_ce;
reg    grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_start_reg;
wire    ap_CS_fsm_state2;
reg    grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire   [31:0] grp_fu_97_p2;
wire   [31:0] grp_fu_161_p2;
reg   [31:0] grp_fu_161_p0;
reg   [31:0] grp_fu_161_p1;
reg    grp_fu_161_ce;
wire   [31:0] grp_fu_165_p2;
reg   [31:0] grp_fu_165_p0;
reg   [31:0] grp_fu_165_p1;
reg    grp_fu_165_ce;
wire   [0:0] grp_fu_169_p2;
reg   [31:0] grp_fu_169_p0;
reg   [31:0] grp_fu_169_p1;
reg    grp_fu_169_ce;
reg   [4:0] grp_fu_169_opcode;
wire   [31:0] grp_fu_173_p2;
reg   [31:0] grp_fu_173_p0;
reg   [31:0] grp_fu_173_p1;
reg   [1:0] grp_fu_173_opcode;
reg    grp_fu_173_ce;
wire    ap_CS_fsm_state20;
reg   [19:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 20'd1;
#0 grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_start_reg = 1'b0;
#0 grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_start_reg = 1'b0;
end

MAC_MAC_Pipeline_VITIS_LOOP_26_1 grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_start),
    .ap_done(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_done),
    .ap_idle(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_idle),
    .ap_ready(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_ready),
    .c(c),
    .b(b),
    .j(j),
    .a(a),
    .z_5_out(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_z_5_out),
    .z_5_out_ap_vld(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_z_5_out_ap_vld),
    .grp_fu_161_p_din0(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_161_p_din0),
    .grp_fu_161_p_din1(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_161_p_din1),
    .grp_fu_161_p_dout0(grp_fu_161_p2),
    .grp_fu_161_p_ce(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_161_p_ce),
    .grp_fu_165_p_din0(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_165_p_din0),
    .grp_fu_165_p_din1(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_165_p_din1),
    .grp_fu_165_p_dout0(grp_fu_165_p2),
    .grp_fu_165_p_ce(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_165_p_ce),
    .grp_fu_169_p_din0(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_169_p_din0),
    .grp_fu_169_p_din1(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_169_p_din1),
    .grp_fu_169_p_opcode(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_169_p_opcode),
    .grp_fu_169_p_dout0(grp_fu_169_p2),
    .grp_fu_169_p_ce(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_169_p_ce),
    .grp_fu_173_p_din0(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_173_p_din0),
    .grp_fu_173_p_din1(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_173_p_din1),
    .grp_fu_173_p_opcode(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_173_p_opcode),
    .grp_fu_173_p_dout0(grp_fu_173_p2),
    .grp_fu_173_p_ce(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_173_p_ce)
);

MAC_MAC_Pipeline_VITIS_LOOP_56_2 grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_start),
    .ap_done(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_done),
    .ap_idle(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_idle),
    .ap_ready(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_ready),
    .z_5_reload(grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_z_5_out),
    .j(j),
    .x_2_out(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_x_2_out),
    .x_2_out_ap_vld(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_x_2_out_ap_vld),
    .y_out(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_y_out),
    .y_out_ap_vld(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_y_out_ap_vld),
    .grp_fu_173_p_din0(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_173_p_din0),
    .grp_fu_173_p_din1(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_173_p_din1),
    .grp_fu_173_p_opcode(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_173_p_opcode),
    .grp_fu_173_p_dout0(grp_fu_173_p2),
    .grp_fu_173_p_ce(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_173_p_ce),
    .grp_fu_161_p_din0(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_161_p_din0),
    .grp_fu_161_p_din1(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_161_p_din1),
    .grp_fu_161_p_dout0(grp_fu_161_p2),
    .grp_fu_161_p_ce(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_161_p_ce),
    .grp_fu_165_p_din0(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_165_p_din0),
    .grp_fu_165_p_din1(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_165_p_din1),
    .grp_fu_165_p_dout0(grp_fu_165_p2),
    .grp_fu_165_p_ce(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_165_p_ce),
    .grp_fu_169_p_din0(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_169_p_din0),
    .grp_fu_169_p_din1(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_169_p_din1),
    .grp_fu_169_p_opcode(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_169_p_opcode),
    .grp_fu_169_p_dout0(grp_fu_169_p2),
    .grp_fu_169_p_ce(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_169_p_ce)
);

MAC_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U21(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_y_out),
    .din1(grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_x_2_out),
    .ce(1'b1),
    .dout(grp_fu_97_p2)
);

MAC_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U22(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_161_p0),
    .din1(grp_fu_161_p1),
    .ce(grp_fu_161_ce),
    .dout(grp_fu_161_p2)
);

MAC_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U23(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_165_p0),
    .din1(grp_fu_165_p1),
    .ce(grp_fu_165_ce),
    .dout(grp_fu_165_p2)
);

MAC_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U24(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_169_p0),
    .din1(grp_fu_169_p1),
    .ce(grp_fu_169_ce),
    .opcode(grp_fu_169_opcode),
    .dout(grp_fu_169_p2)
);

MAC_faddfsub_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_7_full_dsp_1_U25(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_173_p0),
    .din1(grp_fu_173_p1),
    .opcode(grp_fu_173_opcode),
    .ce(grp_fu_173_ce),
    .dout(grp_fu_173_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_start_reg <= 1'b1;
        end else if ((grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_ready == 1'b1)) begin
            grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_start_reg <= 1'b1;
        end else if ((grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_ready == 1'b1)) begin
            grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_start_reg <= 1'b0;
        end
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_161_ce = grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_161_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_161_ce = grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_161_p_ce;
    end else begin
        grp_fu_161_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_161_p0 = grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_161_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_161_p0 = grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_161_p_din0;
    end else begin
        grp_fu_161_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_161_p1 = grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_161_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_161_p1 = grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_161_p_din1;
    end else begin
        grp_fu_161_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_165_ce = grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_165_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_165_ce = grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_165_p_ce;
    end else begin
        grp_fu_165_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_165_p0 = grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_165_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_165_p0 = grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_165_p_din0;
    end else begin
        grp_fu_165_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_165_p1 = grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_165_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_165_p1 = grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_165_p_din1;
    end else begin
        grp_fu_165_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_169_ce = grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_169_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_169_ce = grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_169_p_ce;
    end else begin
        grp_fu_169_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_169_opcode = grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_169_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_169_opcode = grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_169_p_opcode;
    end else begin
        grp_fu_169_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_169_p0 = grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_169_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_169_p0 = grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_169_p_din0;
    end else begin
        grp_fu_169_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_169_p1 = grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_169_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_169_p1 = grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_169_p_din1;
    end else begin
        grp_fu_169_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_173_ce = grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_173_p_ce;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_173_ce = grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_173_p_ce;
    end else begin
        grp_fu_173_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_173_opcode = grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_173_p_opcode;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_173_opcode = grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_173_p_opcode;
    end else begin
        grp_fu_173_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_173_p0 = grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_173_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_173_p0 = grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_173_p_din0;
    end else begin
        grp_fu_173_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_173_p1 = grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_grp_fu_173_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_173_p1 = grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_grp_fu_173_p_din1;
    end else begin
        grp_fu_173_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_return = grp_fu_97_p2;

assign grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_start = grp_MAC_Pipeline_VITIS_LOOP_26_1_fu_74_ap_start_reg;

assign grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_start = grp_MAC_Pipeline_VITIS_LOOP_56_2_fu_87_ap_start_reg;

endmodule //MAC
