// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="neuron_neuron,hls_ip_2022_2,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7a35t-cpg236-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.097000,HLS_SYN_LAT=110,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=1531,HLS_SYN_LUT=1414,HLS_VERSION=2022_2}" *)

module neuron (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        angle,
        sel,
        ap_return
);

parameter    ap_ST_fsm_state1 = 32'd1;
parameter    ap_ST_fsm_state2 = 32'd2;
parameter    ap_ST_fsm_state3 = 32'd4;
parameter    ap_ST_fsm_state4 = 32'd8;
parameter    ap_ST_fsm_state5 = 32'd16;
parameter    ap_ST_fsm_state6 = 32'd32;
parameter    ap_ST_fsm_state7 = 32'd64;
parameter    ap_ST_fsm_state8 = 32'd128;
parameter    ap_ST_fsm_state9 = 32'd256;
parameter    ap_ST_fsm_state10 = 32'd512;
parameter    ap_ST_fsm_state11 = 32'd1024;
parameter    ap_ST_fsm_state12 = 32'd2048;
parameter    ap_ST_fsm_state13 = 32'd4096;
parameter    ap_ST_fsm_state14 = 32'd8192;
parameter    ap_ST_fsm_state15 = 32'd16384;
parameter    ap_ST_fsm_state16 = 32'd32768;
parameter    ap_ST_fsm_state17 = 32'd65536;
parameter    ap_ST_fsm_state18 = 32'd131072;
parameter    ap_ST_fsm_state19 = 32'd262144;
parameter    ap_ST_fsm_state20 = 32'd524288;
parameter    ap_ST_fsm_state21 = 32'd1048576;
parameter    ap_ST_fsm_state22 = 32'd2097152;
parameter    ap_ST_fsm_state23 = 32'd4194304;
parameter    ap_ST_fsm_state24 = 32'd8388608;
parameter    ap_ST_fsm_state25 = 32'd16777216;
parameter    ap_ST_fsm_state26 = 32'd33554432;
parameter    ap_ST_fsm_state27 = 32'd67108864;
parameter    ap_ST_fsm_state28 = 32'd134217728;
parameter    ap_ST_fsm_state29 = 32'd268435456;
parameter    ap_ST_fsm_state30 = 32'd536870912;
parameter    ap_ST_fsm_state31 = 32'd1073741824;
parameter    ap_ST_fsm_state32 = 32'd2147483648;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] angle;
input  [31:0] sel;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [31:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] grp_fu_64_p2;
reg   [31:0] reg_77;
wire    ap_CS_fsm_state9;
reg   [0:0] icmp_ln38_reg_122;
wire    ap_CS_fsm_state16;
wire   [0:0] icmp_ln38_fu_83_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] grp_fu_69_p2;
reg   [31:0] add1_reg_133;
wire   [31:0] grp_fu_73_p2;
reg   [31:0] tan_hyperbolic_reg_138;
wire    ap_CS_fsm_state25;
wire    grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_start;
wire    grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_done;
wire    grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_idle;
wire    grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_ready;
wire   [31:0] grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_x_2_out;
wire    grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_x_2_out_ap_vld;
wire   [31:0] grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_y_out;
wire    grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_y_out_ap_vld;
wire   [31:0] grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_64_p_din0;
wire   [31:0] grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_64_p_din1;
wire   [1:0] grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_64_p_opcode;
wire    grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_64_p_ce;
wire   [31:0] grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_69_p_din0;
wire   [31:0] grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_69_p_din1;
wire   [1:0] grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_69_p_opcode;
wire    grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_69_p_ce;
reg    grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_start_reg;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state10;
reg   [31:0] grp_fu_64_p0;
reg   [31:0] grp_fu_64_p1;
reg   [31:0] grp_fu_69_p0;
reg   [31:0] grp_fu_69_p1;
reg   [31:0] grp_fu_73_p0;
reg   [31:0] grp_fu_73_p1;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state32;
reg   [1:0] grp_fu_64_opcode;
reg    grp_fu_64_ce;
reg    grp_fu_69_ce;
reg   [31:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 32'd1;
#0 grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_start_reg = 1'b0;
end

neuron_neuron_Pipeline_VITIS_LOOP_15_1 grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_start),
    .ap_done(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_done),
    .ap_idle(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_idle),
    .ap_ready(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_ready),
    .angle(angle),
    .x_2_out(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_x_2_out),
    .x_2_out_ap_vld(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_x_2_out_ap_vld),
    .y_out(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_y_out),
    .y_out_ap_vld(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_y_out_ap_vld),
    .grp_fu_64_p_din0(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_64_p_din0),
    .grp_fu_64_p_din1(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_64_p_din1),
    .grp_fu_64_p_opcode(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_64_p_opcode),
    .grp_fu_64_p_dout0(grp_fu_64_p2),
    .grp_fu_64_p_ce(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_64_p_ce),
    .grp_fu_69_p_din0(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_69_p_din0),
    .grp_fu_69_p_din1(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_69_p_din1),
    .grp_fu_69_p_opcode(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_69_p_opcode),
    .grp_fu_69_p_dout0(grp_fu_69_p2),
    .grp_fu_69_p_ce(grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_69_p_ce)
);

neuron_faddfsub_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_7_full_dsp_1_U12(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_64_p0),
    .din1(grp_fu_64_p1),
    .opcode(grp_fu_64_opcode),
    .ce(grp_fu_64_ce),
    .dout(grp_fu_64_p2)
);

neuron_fadd_32ns_32ns_32_7_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_7_full_dsp_1_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_69_p0),
    .din1(grp_fu_69_p1),
    .ce(grp_fu_69_ce),
    .dout(grp_fu_69_p2)
);

neuron_fdiv_32ns_32ns_32_16_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 16 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fdiv_32ns_32ns_32_16_no_dsp_1_U14(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_73_p0),
    .din1(grp_fu_73_p1),
    .ce(1'b1),
    .dout(grp_fu_73_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_start_reg <= 1'b1;
        end else if ((grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_ready == 1'b1)) begin
            grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_reg_122 == 1'd1) & (1'b1 == ap_CS_fsm_state16))) begin
        add1_reg_133 <= grp_fu_69_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        icmp_ln38_reg_122 <= icmp_ln38_fu_83_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln38_reg_122 == 1'd1) & (1'b1 == ap_CS_fsm_state16)) | ((icmp_ln38_reg_122 == 1'd1) & (1'b1 == ap_CS_fsm_state9)))) begin
        reg_77 <= grp_fu_64_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln38_reg_122 == 1'd0) & (1'b1 == ap_CS_fsm_state25))) begin
        tan_hyperbolic_reg_138 <= grp_fu_73_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state32)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_64_ce = grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_64_p_ce;
    end else begin
        grp_fu_64_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_64_opcode = grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_64_p_opcode;
    end else if ((((icmp_ln38_reg_122 == 1'd1) & (1'b1 == ap_CS_fsm_state10)) | ((icmp_ln38_reg_122 == 1'd1) & (1'b1 == ap_CS_fsm_state3)))) begin
        grp_fu_64_opcode = 2'd0;
    end else begin
        grp_fu_64_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_64_p0 = grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_64_p_din0;
    end else if (((1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_64_p0 = grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_y_out;
    end else begin
        grp_fu_64_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_64_p1 = grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_64_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_64_p1 = grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_x_2_out;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_64_p1 = 32'd1065353216;
    end else begin
        grp_fu_64_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_69_ce = grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_69_p_ce;
    end else begin
        grp_fu_69_ce = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_69_p0 = grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_69_p_din0;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_69_p0 = reg_77;
    end else begin
        grp_fu_69_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_69_p1 = grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_grp_fu_69_p_din1;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_69_p1 = grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_x_2_out;
    end else begin
        grp_fu_69_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_73_p0 = reg_77;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_73_p0 = grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_y_out;
    end else begin
        grp_fu_73_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_73_p1 = add1_reg_133;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_73_p1 = grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_x_2_out;
    end else begin
        grp_fu_73_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return = ((icmp_ln38_reg_122[0:0] == 1'b1) ? grp_fu_73_p2 : tan_hyperbolic_reg_138);

assign grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_start = grp_neuron_Pipeline_VITIS_LOOP_15_1_fu_54_ap_start_reg;

assign icmp_ln38_fu_83_p2 = ((sel != 32'd0) ? 1'b1 : 1'b0);

endmodule //neuron
