#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Nov 08 15:16:25 IST 2024
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim blk_tb_func_synth -key {Post-Synthesis:sim_1:Functional:blk_tb} -tclbatch blk_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim blk_tb_func_synth -key {Post-Synthesis:sim_1:Functional:blk_tb} -tclbatch blk_tb.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

