# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/chait/OneDrive/Desktop/FPGA/Project/tanh/hyperbolic_tan/hyperbolic_tan.srcs/sources_1/ip/tanh_custom_0/tanh_custom_0.xci
# IP: The module: 'tanh_custom_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chait/OneDrive/Desktop/FPGA/Project/tanh/hyperbolic_tan/hyperbolic_tan.gen/sources_1/ip/tanh_custom_0/constraints/tanh_custom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tanh_custom_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/chait/OneDrive/Desktop/FPGA/Project/tanh/hyperbolic_tan/hyperbolic_tan.srcs/sources_1/ip/tanh_custom_0/tanh_custom_0.xci
# IP: The module: 'tanh_custom_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chait/OneDrive/Desktop/FPGA/Project/tanh/hyperbolic_tan/hyperbolic_tan.gen/sources_1/ip/tanh_custom_0/constraints/tanh_custom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tanh_custom_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
