# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/chait/OneDrive/Desktop/FPGA/Project/tanh/neuron_ipcheck/neuron_ipcheck.srcs/sources_1/ip/MAC_0/MAC_0.xci
# IP: The module: 'MAC_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chait/OneDrive/Desktop/FPGA/Project/tanh/neuron_ipcheck/neuron_ipcheck.gen/sources_1/ip/MAC_0/constraints/MAC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MAC_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/chait/OneDrive/Desktop/FPGA/Project/tanh/neuron_ipcheck/neuron_ipcheck.srcs/sources_1/ip/MAC_0/MAC_0.xci
# IP: The module: 'MAC_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/chait/OneDrive/Desktop/FPGA/Project/tanh/neuron_ipcheck/neuron_ipcheck.gen/sources_1/ip/MAC_0/constraints/MAC_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MAC_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
